# Generated by Django 4.2.15 on 2024-08-27 17:08

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='items',
            name='imagen',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/items'), upload_to=''),
        ),
    ]
