# Generated by Django 4.2.15 on 2024-08-27 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_descripción_items_descripcion_items_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
