# Generated by Django 4.2.15 on 2024-09-02 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_pedido_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorias',
            new_name='Categoria',
        ),
    ]
