# Generated by Django 4.2.15 on 2024-10-02 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_pedido_items_usuario_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.item')),
                ('pedido_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.pedido')),
            ],
        ),
    ]
