# Generated by Django 4.2.15 on 2024-10-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_pedido_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido_items',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='pedido_items',
            old_name='pedido_id',
            new_name='pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='items',
            field=models.ManyToManyField(through='base.Pedido_Items', to='base.item'),
        ),
    ]
