# Generated by Django 4.2.15 on 2024-10-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_rename_item_id_pedido_items_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
