# Generated by Django 4.2.15 on 2024-10-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_usuario_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='entregado',
            new_name='enviado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
