# Generated by Django 4.2.15 on 2024-10-07 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_rename_entregado_pedido_enviado_pedido_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
